name: CARPA CI/CD

on:
  push:
    branches: [master, develop]
  pull_request:
    branches:  [master, develop]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
        django-version: [ 3.1 ]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Django==${{ matrix.django-version }}

  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Dokku deploy
        uses: vitalyliber/dokku-github-action@v6.0
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: 157.230.57.158
          PROJECT: carpa
          APP_CONFIG: ${{ secrets.APP_CONFIG }}
