name: CARPA CI/CD

on:
  push:
    branches: [master, develop]
  pull_request:
    branches:  [master, develop]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
        django-version: [ 3.1 ]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Django==${{ matrix.django-version }}

  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@157.230.57.158:22'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
